from datahub.configuration.common import ConfigModel


class AirbyteConnectionSourceConfig(ConfigModel):
    """Configuration for a single Airbyte connection to register in DataHub.

    Each field maps to a ``${ENV_VAR}`` placeholder in the recipe YAML so that
    the same recipe can be reused across connections by swapping env vars.

    Attributes:
        airflow_dag:
            Name of the Airflow DAG that triggers the Airbyte sync.
            Used to build both the Airbyte DataFlow URN and the upstream
            Airflow DataJob URN.  Example: ``"hackernews_rss_bigquery"``.
        airflow_task:
            Task ID inside the Airflow DAG that triggers the sync.
            Used to build the upstream Airflow DataJob URN so that lineage
            connects the Airflow task to the Airbyte connection.
            Example: ``"hackernews_rss_front"``.
        airbyte_connection_id:
            UUID of the Airbyte connection.  Used as the
            DataJob ID so it is unique and traceable back to Airbyte.
            Example: ``"e37988e6-8ed5-465c-abb2-150639819c62"``.
        airbyte_client_id:
            Client ID for Airbyte API authentication.
        airbyte_client_secret:
            Client secret for Airbyte API authentication.
        airbyte_server_url:
            Base URL of the Airbyte API.  Defaults to Airbyte Cloud (``https://api.airbyte.com/v1``).
            For self-hosted instances use e.g. ``http://localhost:8000/api/public/v1/``.
        environment:
            DataHub environment label (``"prod"``, ``"dev"``, etc.).
            Defaults to ``"prod"``.  Appears in every URN generated by this source.
    """

    airflow_dag: str
    airflow_task: str
    airbyte_connection_id: str
    airbyte_client_id: str
    airbyte_client_secret: str
    airbyte_server_url: str = "https://api.airbyte.com/v1"
    environment: str = "prod"
