x-datahub-gms-image: &datahub-gms-image acryldata/datahub-gms:${DATAHUB_VERSION:-v1.6.0}
x-datahub-frontend-image: &datahub-frontend-image acryldata/datahub-frontend-react:${DATAHUB_VERSION:-v1.6.0}
x-datahub-mae-consumer-image: &datahub-mae-consumer-image acryldata/datahub-mae-consumer:${DATAHUB_VERSION:-v1.6.0}
x-datahub-mce-consumer-image: &datahub-mce-consumer-image acryldata/datahub-mce-consumer:${DATAHUB_VERSION:-v1.6.0}
x-datahub-upgrade-image: &datahub-upgrade-image acryldata/datahub-upgrade:${DATAHUB_VERSION:-v1.6.0}

x-postgres-image: &postgres-image postgres:${POSTGRES_VERSION:-18-alpine}
x-opensearch-image: &opensearch-image opensearchproject/opensearch:${DATAHUB_SEARCH_TAG:-2.19.6}
x-cp-kafka-image: &cp-kafka-image confluentinc/cp-kafka:${CONFLUENT_PLATFORM_VERSION:-8.2.2}
x-cp-schema-registry-image: &cp-schema-registry-image confluentinc/cp-schema-registry:${CONFLUENT_PLATFORM_VERSION:-8.2.2}

x-conduktor-console: &conduktor-console-image conduktor/conduktor-console:${CONDUKTOR_PLATFORM_VERSION:-1.46.1}
x-conduktor-cortex: &conduktor-cortex-image conduktor/conduktor-console-cortex:${CONDUKTOR_PLATFORM_VERSION:-1.46.1}

x-kafka-common:
  &kafka-common
  image: *cp-kafka-image
  environment: &kafka-common-env
    CLUSTER_ID: 'K9qYnkFwaAFO1DrFubmKug=='
    KAFKA_PROCESS_ROLES: 'broker,controller'
    KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
    KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT'
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    KAFKA_DELETE_TOPIC_ENABLE: true
    KAFKA_JMX_PORT: 9999
  healthcheck:
    test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:29092 || exit 1"]
    start_period: 10s
    interval: 5s
    timeout: 10s
    retries: 5
  restart: on-failure:5

x-depends-on-kafka-cluster:
  depends_on: &depends-on-kafka-cluster
    datahub-kafka-broker0:
      condition: service_healthy
    datahub-schema-registry:
      condition: service_healthy

services:
  # Infrastructure
  datahub-postgres:
    image: *postgres-image
    container_name: datahub-postgres
    hostname: datahub-postgres
    environment:
      POSTGRES_DB: 'datahub'
      POSTGRES_USER: 'datahub'
      POSTGRES_PASSWORD: 'datahub'
    ports:
      - ${DATAHUB_MAPPED_POSTGRES_PORT:-5439}:5432
    volumes:
      - vol-datahub-pgdata:/var/lib/postgresql
    healthcheck:
      interval: 5s
      retries: 5
      start_period: 20s
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      timeout: 10s
    restart: on-failure

  datahub-opensearch:
    image: *opensearch-image
    container_name: datahub-opensearch
    hostname: datahub-opensearch
    environment:
      discovery.type: 'single-node'
      DISABLE_SECURITY_PLUGIN: true
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: 'admin'
      OPENSEARCH_JAVA_OPTS: '-Xms768m -Xmx1024m -Dlog4j2.formatMsgNoLookups=true'
    ports:
      - ${DATAHUB_MAPPED_ELASTIC_PORT:-9200}:9200
    volumes:
      - vol-datahub-osdata:/usr/share/opensearch/data
    deploy:
      resources:
        limits:
          memory: 1G
    healthcheck:
      interval: 5s
      retries: 5
      start_period: 30s
      test: curl -sS --fail http://datahub-opensearch:$${DATAHUB_ELASTIC_PORT:-9200}/_cluster/health?wait_for_status=yellow&timeout=0s
      timeout: 10s
    restart: on-failure:5

  datahub-kafka-broker0:
    <<: *kafka-common
    container_name: datahub-kafka-broker0
    hostname: datahub-kafka-broker0
    environment:
      <<: *kafka-common-env
      KAFKA_NODE_ID: 0
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,EXTERNAL://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://datahub-kafka-broker0:29092,EXTERNAL://localhost:9092,DOCKER://host.docker.internal:9093
      KAFKA_CONTROLLER_QUORUM_VOTERS: '0@datahub-kafka-broker0:29093'
    ports:
      - '9092:9092'
      - '9093:9093'
    volumes:
      - vol-datahub-kafka-broker0:/var/lib/kafka/data

  datahub-schema-registry:
    image: *cp-schema-registry-image
    container_name: datahub-schema-registry
    hostname: datahub-schema-registry
    environment:
      SCHEMA_REGISTRY_HOST_NAME: 'datahub-schema-registry'
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'PLAINTEXT://datahub-kafka-broker0:29092'
      SCHEMA_REGISTRY_LISTENERS: 'http://0.0.0.0:8081'
      SCHEMA_REGISTRY_DEBUG: true
    ports:
      - '8081:8081'
    depends_on:
      datahub-kafka-broker0:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/subjects || exit 1"]
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 5
    restart: on-failure:5

  # DataHub Core Docs
  # https://docs.datahub.com/docs/deploy/environment-vars
  # Ref.: https://github.com/datahub-project/datahub/blob/releases/v1.6.0/docker/datahub-gms/env/docker-without-neo4j.env
  datahub-gms:
    image: *datahub-gms-image
    container_name: datahub-gms
    hostname: datahub-gms
    environment:
      # Metadata db (PostgreSQL)
      EBEAN_DATASOURCE_HOST: 'datahub-postgres:5432'
      EBEAN_DATASOURCE_USERNAME: 'datahub'
      EBEAN_DATASOURCE_PASSWORD: 'datahub'
      EBEAN_DATASOURCE_URL: 'jdbc:postgresql://datahub-postgres:5432/datahub'
      EBEAN_DATASOURCE_DRIVER: 'org.postgresql.Driver'
      # Full-text search (OpenSearch)
      ELASTICSEARCH_HOST: 'datahub-opensearch'
      ELASTICSEARCH_PORT: 9200
      ELASTICSEARCH_INDEX_BUILDER_MAPPINGS_REINDEX: true
      ELASTICSEARCH_INDEX_BUILDER_SETTINGS_REINDEX: true
      ES_BULK_REFRESH_POLICY: 'NONE'
      # Graph db
      GRAPH_SERVICE_IMPL: 'elasticsearch'
      GRAPH_SERVICE_DIFF_MODE_ENABLED: true
      # Kafka
      KAFKA_BOOTSTRAP_SERVER: 'datahub-kafka-broker0:29092'
      KAFKA_SCHEMAREGISTRY_URL: 'http://datahub-schema-registry:8081'
      KAFKA_CONSUMER_STOP_ON_DESERIALIZATION_ERROR: ${KAFKA_CONSUMER_STOP_ON_DESERIALIZATION_ERROR:-true}
      DATAHUB_UPGRADE_HISTORY_KAFKA_CONSUMER_GROUP_ID: 'generic-duhe-consumer-job-client-gms'
      # Auth
      METADATA_SERVICE_AUTH_ENABLED: ${METADATA_SERVICE_AUTH_ENABLED:-false}
      DATAHUB_TOKEN_SERVICE_SIGNING_KEY: ${DATAHUB_TOKEN_SERVICE_SIGNING_KEY:-WnEdIeTG/VVCLQqGwC/BAkqyY0k+H8NEAtWGejrBI94=}
      DATAHUB_TOKEN_SERVICE_SALT: ${DATAHUB_TOKEN_SERVICE_SALT:-ohDVbJBvHHVJh9S/UA7vkJ5SOkC3U0ER3bAQqOIaPus=}
      # Consumers (disable when running mae- and mce- as standalone consumers)
      MCP_CONSUMER_ENABLED: false
      MCL_CONSUMER_ENABLED: false
      PE_CONSUMER_ENABLED: false
      UI_INGESTION_ENABLED: true
      # App config
      DATAHUB_SERVER_TYPE: ${DATAHUB_SERVER_TYPE:-prod}
      INGESTION_REPORTING_ENABLED: true
      DATAHUB_ANALYTICS_ENABLED: false
      ENTITY_SERVICE_ENABLE_RETENTION: true
      ENTITY_REGISTRY_CONFIG_PATH: '/datahub/datahub-gms/resources/entity-registry.yml'
      JAVA_OPTS: '-Xms1g -Xmx4g'
    ports:
      - '9090:8080'
    volumes:
      - ${HOME}/.datahub/plugins:/etc/datahub/plugins
    depends_on:
      datahub-upgrade:
        condition: service_completed_successfully
    healthcheck:
      interval: 5s
      retries: 5
      start_period: 90s
      test: curl -sS --fail http://datahub-gms:${DATAHUB_GMS_PORT:-8080}/health
      timeout: 10s

  # Ref.: https://github.com/datahub-project/datahub/blob/releases/v1.6.0/docker/datahub-frontend/env/docker.env
  datahub-frontend:
    image: *datahub-frontend-image
    container_name: datahub-frontend
    hostname: datahub-frontend
    environment:
      # GMS connection
      DATAHUB_GMS_HOST: 'datahub-gms'
      DATAHUB_GMS_PORT: 8080
      DATAHUB_SECRET: '7Xa4#E6ss84ocB3?k9&CPN#Gk?zS&3aeDydx93pa'
      DATAHUB_APP_VERSION: ${DATAHUB_VERSION:-v1.6.0}
      DATAHUB_PLAY_MEM_BUFFER_SIZE: '10MB'
      JAVA_OPTS: '-Xms512m -Xmx2g -Dhttp.port=9002 -Dconfig.file=datahub-frontend/conf/application.conf -Djava.security.auth.login.config=datahub-frontend/conf/jaas.conf -Dlogback.configurationFile=datahub-frontend/conf/logback.xml -Dlogback.debug=false -Dpidfile.path=/dev/null'
      # Elastic/OpenSearch client config (Analytics)
      ELASTIC_CLIENT_HOST: 'datahub-opensearch'
      ELASTIC_CLIENT_PORT: 9200
      # Kafka
      KAFKA_BOOTSTRAP_SERVER: 'datahub-kafka-broker0:29092'
      DATAHUB_TRACKING_TOPIC: 'DataHubUsageEvent_v1'
      # App config
      FRONTEND_GRACEFUL_SHUTDOWN_ENABLED: 'true'
    ports:
      - ${DATAHUB_MAPPED_FRONTEND_PORT:-9002}:9002
    volumes:
      - ${HOME}/.datahub/plugins:/etc/datahub/plugins
    depends_on:
      datahub-gms:
        condition: service_healthy

  # Ref.: https://github.com/datahub-project/datahub/blob/releases/v1.6.0/docker/datahub-mce-consumer/env/docker-without-neo4j.env
  # Writes to DataHub GMS
  datahub-mce-consumer:
    image: *datahub-mce-consumer-image
    container_name: datahub-mce-consumer
    hostname: datahub-mce-consumer
    environment:
      # Consumer config
      DATAHUB_UPGRADE_HISTORY_KAFKA_CONSUMER_GROUP_ID: 'datahub-mce-consumer-grp'
      MCP_CONSUMER_ENABLED: true
      MCL_CONSUMER_ENABLED: false
      PE_CONSUMER_ENABLED: false
      # GMS connection & auth
      DATAHUB_TOKEN_SERVICE_SIGNING_KEY: ${DATAHUB_TOKEN_SERVICE_SIGNING_KEY:-WnEdIeTG/VVCLQqGwC/BAkqyY0k+H8NEAtWGejrBI94=}
      DATAHUB_TOKEN_SERVICE_SALT: ${DATAHUB_TOKEN_SERVICE_SALT:-ohDVbJBvHHVJh9S/UA7vkJ5SOkC3U0ER3bAQqOIaPus=}
      # Metadata db (PostgreSQL)
      EBEAN_DATASOURCE_HOST: 'datahub-postgres:5432'
      EBEAN_DATASOURCE_USERNAME: 'datahub'
      EBEAN_DATASOURCE_PASSWORD: 'datahub'
      EBEAN_DATASOURCE_URL: 'jdbc:postgresql://datahub-postgres:5432/datahub'
      EBEAN_DATASOURCE_DRIVER: 'org.postgresql.Driver'
      # Full-text search (OpenSearch)
      ELASTICSEARCH_HOST: 'datahub-opensearch'
      ELASTICSEARCH_PORT: 9200
      ES_BULK_REFRESH_POLICY: 'NONE'
      # Graph db
      GRAPH_SERVICE_IMPL: 'elasticsearch'
      GRAPH_SERVICE_DIFF_MODE_ENABLED: true
      # Kafka
      KAFKA_BOOTSTRAP_SERVER: 'datahub-kafka-broker0:29092'
      KAFKA_SCHEMAREGISTRY_URL: 'http://datahub-schema-registry:8081'
      KAFKA_CONSUMER_HEALTH_CHECK_ENABLED: ${KAFKA_CONSUMER_HEALTH_CHECK_ENABLED:-true}
      # App config
      DATAHUB_SERVER_TYPE: ${DATAHUB_SERVER_TYPE:-prod}
      DATAHUB_TELEMETRY_ENABLED: ${DATAHUB_TELEMETRY_ENABLED:-true}
      DATAHUB_SYSTEM_CLIENT_ID: '__datahub_system'
      DATAHUB_SYSTEM_CLIENT_SECRET: 'JohnSnowKnowsNothing'
      ENTITY_SERVICE_ENABLE_RETENTION: true
      ENTITY_REGISTRY_CONFIG_PATH: '/datahub/datahub-mce-consumer/resources/entity-registry.yml'
      JAVA_OPTS: '-Xms1g -Xmx1g'
    depends_on:
      datahub-gms:
        condition: service_healthy

  # Ref.: https://github.com/datahub-project/datahub/blob/releases/v1.6.0/docker/datahub-mae-consumer/env/docker-without-neo4j.env
  # Writes to Elasticsearch/Opensearch & Neo4j
  datahub-mae-consumer:
    image: *datahub-mae-consumer-image
    container_name: datahub-mae-consumer
    hostname: datahub-mae-consumer
    environment:
      # Consumer config
      MCP_CONSUMER_ENABLED: false
      MCL_CONSUMER_ENABLED: true
      PE_CONSUMER_ENABLED: true
      UI_INGESTION_ENABLED: true
      DATAHUB_UPGRADE_HISTORY_KAFKA_CONSUMER_GROUP_ID: 'datahub-mae-consumer-grp'
      # GMS connection
      DATAHUB_GMS_HOST: 'datahub-gms'
      DATAHUB_GMS_PORT: 8080
      DATAHUB_ANALYTICS_ENABLED: 'false'
      # Full-text search (OpenSearch)
      ELASTICSEARCH_HOST: 'datahub-opensearch'
      ELASTICSEARCH_PORT: 9200
      ES_BULK_REFRESH_POLICY: 'NONE'
      # Graph db
      GRAPH_SERVICE_IMPL: 'elasticsearch'
      # Kafka
      KAFKA_BOOTSTRAP_SERVER: 'datahub-kafka-broker0:29092'
      KAFKA_SCHEMAREGISTRY_URL: 'http://datahub-schema-registry:8081'
      KAFKA_CONSUMER_STOP_ON_DESERIALIZATION_ERROR: ${KAFKA_CONSUMER_STOP_ON_DESERIALIZATION_ERROR:-true}
      KAFKA_CONSUMER_HEALTH_CHECK_ENABLED: ${KAFKA_CONSUMER_HEALTH_CHECK_ENABLED:-true}
      ENTITY_REGISTRY_CONFIG_PATH: '/datahub/datahub-mae-consumer/resources/entity-registry.yml'
    depends_on:
      datahub-gms:
        condition: service_healthy

  # Ref.: https://github.com/datahub-project/datahub/blob/releases/v1.6.0/docker/datahub-upgrade/env/docker-without-neo4j.env
  datahub-upgrade:
    image: *datahub-upgrade-image
    container_name: datahub-upgrade
    hostname: datahub-upgrade
    command:
      - -u
      - SystemUpdate
    environment:
      # Metadata db (PostgreSQL)
      EBEAN_DATASOURCE_HOST: 'datahub-postgres:5432'
      EBEAN_DATASOURCE_USERNAME: 'datahub'
      EBEAN_DATASOURCE_PASSWORD: 'datahub'
      EBEAN_DATASOURCE_URL: 'jdbc:postgresql://datahub-postgres:5432/datahub'
      EBEAN_DATASOURCE_DRIVER: 'org.postgresql.Driver'
      # Kafka
      KAFKA_BOOTSTRAP_SERVER: 'datahub-kafka-broker0:29092'
      KAFKA_SCHEMAREGISTRY_URL: 'http://datahub-schema-registry:8081'
      # Full-text search (OpenSearch)
      ELASTICSEARCH_HOST: 'datahub-opensearch'
      ELASTICSEARCH_PORT: 9200
      ELASTICSEARCH_INDEX_BUILDER_MAPPINGS_REINDEX: 'false'
      ELASTICSEARCH_INDEX_BUILDER_SETTINGS_REINDEX: 'false'
      ELASTICSEARCH_BUILD_INDICES_CLONE_INDICES: 'true'
      # Graph db
      GRAPH_SERVICE_IMPL: 'elasticsearch'
      # GMS connection
      DATAHUB_GMS_PROTOCOL: 'http'
      DATAHUB_GMS_HOST: 'datahub-gms'
      DATAHUB_GMS_PORT: 8080
      DATAHUB_TOKEN_SERVICE_SIGNING_KEY: ${DATAHUB_TOKEN_SERVICE_SIGNING_KEY:-WnEdIeTG/VVCLQqGwC/BAkqyY0k+H8NEAtWGejrBI94=}
      DATAHUB_TOKEN_SERVICE_SALT: ${DATAHUB_TOKEN_SERVICE_SALT:-ohDVbJBvHHVJh9S/UA7vkJ5SOkC3U0ER3bAQqOIaPus=}
      # SystemUpdate
      ENTITY_REGISTRY_CONFIG_PATH: '/datahub/datahub-gms/resources/entity-registry.yml'
      BACKFILL_BROWSE_PATHS_V2: 'true'
      REPROCESS_DEFAULT_BROWSE_PATHS_V2: ${REPROCESS_DEFAULT_BROWSE_PATHS_V2:-false}
      # New in 1.6.0 (replaces elasticsearch-setup and mysql/postgres-setup)
      DATAHUB_SQL_SETUP_ENABLED: 'true'
    depends_on:
      datahub-postgres:
        condition: service_healthy
      datahub-opensearch:
        condition: service_healthy

  # Conduktor Platform Docs:
  # https://docs.conduktor.io/platform/configuration/env-variables
  conduktor-console:
    image: *conduktor-console-image
    container_name: conduktor-console
    hostname: conduktor-console
    environment:
      CDK_CLUSTERS_0_ID: 'kafka-kraft-in-docker'
      CDK_CLUSTERS_0_NAME: 'single-broker-kraft-kafka'
      CDK_CLUSTERS_0_BOOTSTRAPSERVERS: 'datahub-kafka-broker0:29092'
      CDK_CLUSTERS_0_SCHEMAREGISTRY_URL: 'http://datahub-schema-registry:8081'
      CDK_DATABASE_URL: "postgresql://conduktor:conduktor@conduktor-metastore:5432/conduktor"
      CDK_MONITORING_CORTEX-URL: http://conduktor-cortex:9009/
      CDK_MONITORING_ALERT-MANAGER-URL: http://conduktor-cortex:9010/
      CDK_MONITORING_CALLBACK-URL: http://conduktor-console:8080/monitoring/api/
      CDK_MONITORING_NOTIFICATIONS-CALLBACK-URL: http://localhost:8080
      CDK_LISTENING_PORT: 8080
    ports:
      - '9000:8080'
    volumes:
      - vol-conduktor-data:/var/conduktor
    depends_on:
      <<: *depends-on-kafka-cluster
      conduktor-metastore:
        condition: service_healthy
    restart: on-failure:5

  conduktor-metastore:
    image: *postgres-image
    container_name: conduktor-metastore
    hostname: conduktor-metastore
    environment:
      POSTGRES_USER: 'conduktor'
      POSTGRES_PASSWORD: 'conduktor'
      POSTGRES_DB: 'conduktor'
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
    ports:
      - '5432'
    volumes:
      - vol-conduktor-metastore:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U conduktor"]
      interval: 5s
      timeout: 10s
      retries: 5
    restart: on-failure:5

  conduktor-cortex:
    image: *conduktor-cortex-image
    container_name: conduktor-cortex
    environment:
      CDK_CONSOLE-URL: "http://conduktor-console:8080"
    ports:
      - "9009:9009" # cortex api
      - "9010:9010" # alertmanager api
      - "9091:9090" # prometheus api
    restart: on-failure:5

volumes:
  vol-datahub-kafka-broker0:
    name: vol-datahub-kafka-broker0
  vol-datahub-pgdata:
    name: vol-datahub-pgdata
  vol-datahub-osdata:
    name: vol-datahub-osdata
  vol-conduktor-data:
    name: vol-conduktor-data
  vol-conduktor-metastore:
    name: vol-conduktor-metastore
